doggie/urls.py
from django.urls import path
from doggie import views
from doggie.views import cmt_add_view

app_name = 'doggie'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('dogcategory/<slug:dogcategory_name_slug>/',views.show_dogcategory, name='show_dogcategory'),
    path('dogcategory/<slug:dogcategory_name_slug>/<slug:dog_name_slug>/',views.show_dog, name='show_dog'),
    path('add_dogcategory/',views.add_dogcategory,name='add_dogcategory'),
    path('add_dog/', views.add_dog, name='add_dog'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('dogcategory/<slug:dogcategory_name_slug>/<slug:dog_name_slug>/add/',views.cmt_add_view, name='cmt_add_url'),
    path('dogcategory/<slug:dogcategory_name_slug>/<slug:dog_name_slug>/like/', views.like_dog, name='like_dog'),

]

doggie_project/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.urls import include
from doggie import views
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from django.conf.urls.static import static
from django.conf import settings

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('doggie:register_profile')

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('doggie/', include('doggie.urls')),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('search/',include('haystack.urls')),
    path('comment/', include('doggie.urls', namespace = 'comment')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doggie/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.
class DogCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'DogCategories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(DogCategory, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Dog(models.Model):
    dogcategory = models.ForeignKey(DogCategory, on_delete=models.CASCADE)
    dog_name = models.CharField(max_length=128, unique=True)
    short_description = models.CharField(max_length=1280)
    long_description = models.CharField(max_length=1280)
    life_span = models.CharField(max_length=128)
    price = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    images = models.ImageField(upload_to='dogs_images', null=True, blank=True)
    slug = models.SlugField(unique=True)
    dogcategory_slug = models.SlugField()

    def save(self, *args, **kwargs):
        if self.likes < 0:
            self.likes = 0
        self.slug = slugify(self.dog_name)
        self.dogcategory_slug = slugify(self.dogcategory)
        super(Dog, self).save(*args, **kwargs)

    def __str__(self):
        return self.dog_name

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username


class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Reviewer')
    body = models.TextField('Comments Content')
    create_date = models.DateTimeField('Time', auto_now_add=True)
    belong = models.ForeignKey(settings.DOG_MODEL, on_delete=models.CASCADE, related_name='dogs_comments', verbose_name='Belongto')

    class Meta:
        verbose_name = 'Comments'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

doggie/forms.py
from django import forms
from doggie.models import DogCategory, Dog, UserProfile
from django.contrib.auth.models import User

class DogCategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="Please enter the Dogcategory name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
    # an association
        model = DogCategory
        fields = ('name',)


class DogForm(forms.ModelForm):
    dogcategory = forms.ModelChoiceField(queryset=DogCategory.objects.all(), empty_label="Choose category",help_text="Select.")
    dog_name = forms.CharField(max_length=128,help_text="Please enter the name of the dog.")
    short_description = forms.CharField(max_length=1280, help_text="Please enter the short description of the dog.")
    long_description = forms.CharField(max_length=1280, help_text="Please enter the long description of the dog.")
    price = forms.IntegerField(max_value=10000, help_text="Please enter the price of the dog.")
    life_span = forms.CharField(max_length=1280, help_text="Please enter the life span of the dog.")

    class Meta:
        model = Dog
        exclude = ('likes','dogcategory_slug','views','slug')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

doggie/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST
from doggie.models import DogCategory
from doggie.models import Dog
from doggie.forms import DogCategoryForm, DogForm
from django.shortcuts import redirect
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from doggie.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth.models import User
from doggie.models import UserProfile ,Comment
from django.views import View
from django.utils.decorators import method_decorator

def index(request):
    request.session.set_test_cookie()

    dogcategory_list = DogCategory.objects.all

    context_dict = {}
    context_dict['boldmessage'] = 'Doggie！！！！!'
    context_dict['dogcategories'] = dogcategory_list


    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'doggie/index.html', context=context_dict)

def about(request):

    return render(request, 'doggie/about.html')


def show_dogcategory(request, dogcategory_name_slug):
    context_dict = {}
    try:
        dogcategory = DogCategory.objects.get(slug=dogcategory_name_slug)
        dog = Dog.objects.filter(dogcategory=dogcategory)
        context_dict['dogs'] = dog
        context_dict['dogcategory'] = dogcategory
    except DogCategory.DoesNotExist:
        context_dict['dogcategory'] = None
        context_dict['dogs'] = None

    return render(request, 'doggie/dogcategory.html', context=context_dict)

def show_dog(request,dogcategory_name_slug, dog_name_slug):

    context_dict = {}

    try:

        dogs = Dog.objects.filter(slug=dog_name_slug)

        context_dict['dogs'] = dogs

    except Dog.DoesNotExist:

        context_dict['dogs'] = None

    dog = get_object_or_404(Dog, slug=dog_name_slug)
    cmt_list = Comment.objects.filter(belong=dog)

    context_dict['dog'] = dog
    context_dict['cmt_list'] = cmt_list
    return render(request, 'doggie/dog.html', context=context_dict)

def add_dogcategory(request):
    form = DogCategoryForm()

    if request.method == 'POST':
        form = DogCategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('doggie:index'))
        else:
            print(form.errors)
    return render(request, 'doggie/add_dogcategory.html', {'form': form})

@login_required
def add_dog(request):
    form = DogForm()
    if request.method == 'POST':
        form = DogForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('doggie:index'))
        else:
            print(form.errors)
    return render(request, 'doggie/add_dog.html', {'form': form})

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'doggie/register.html',
                  context = {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('doggie:index'))
            else:
                return HttpResponse("Your Doggie account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'doggie/login.html')



@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('doggie:index'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()) )
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], "%Y-%m-%d %H:%M:%S")

    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1

        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('doggie:index'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'doggie/profile_registration.html', context_dict)


class ProfileView(View):

    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'picture': user_profile.picture})

        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('doggie:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'doggie/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('doggie:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('doggie:profile',
                                    kwargs={'username': username}))
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'doggie/profile.html', context_dict)

@login_required
@require_POST
def cmt_add_view(request,dogcategory_name_slug, dog_name_slug):
    dogs = Dog.objects.filter(slug=dog_name_slug)
    if request.is_ajax():
        cmt_user = request.user
        cmt_dogid = dogs[0].id
        cmt_body = request.POST.get('body')
        dog = Dog.objects.get(id=cmt_dogid)

        comment = Comment(owner=cmt_user, body=cmt_body, belong=dog)
        comment.save()

        return JsonResponse({'msg':'Your review was submitted successfully！'})
    return JsonResponse({'msg':'Your comment submission failed！'})


@login_required
def like_dog(request,dogcategory_name_slug, dog_name_slug):
    did = None
    dog = Dog.objects.filter(slug=dog_name_slug)
    if request.method == 'GET':
        did = dog[0].id

    likes = 0
    if did:
        dog = Dog.objects.get(id=int(did))
        if dog:
            likes = dog.likes + 1
            dog.likes = likes
            dog.save()
    return HttpResponse(likes)

templates/doggie/about.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Doggie
{% endblock %}

{% block body_block %}
				<section id="aboutus">
				<div class="inner">
<!-- 					<header> -->
					<br/>
					<br/>
						<h3>We are Group X</h3>
						<br/>
					</header>
					<div class="flex flex-4"  style=text-align: center>
						<div class="box person" style=text-align: center;>
							<div class="image round">
								<img src="/media/images/avatar/ssy.png" alt="Person 1" />
							</div>
							<h5> &nbsp&nbsp&nbspSiyu Shang</h5>
							<p> &nbsp&nbsp&nbsp2485408S</p>
						</div>
						<div class="box person">
							<div class="image round">
								<img src="/media/images/avatar/swz.png" alt="Person 2" />
							</div>
							<h5>&nbspWanzhen Sun</h5>
							<p> &nbsp2494274S</p>
						</div>
						<div class="box person">
							<div class="image round">
								<img src="/media/images/avatar/yfy.png" alt="Person 3" />
							</div>
							<h5> &nbsp&nbsp&nbsp&nbspFanyu Ye</h5>
							<p> &nbsp&nbsp&nbsp&nbsp2448797Y</p>
						</div>
						<div class="box person">
							<div class="image round">
								<img src="/media/images/avatar/zzt.png" alt="Person 4" />
							</div>
							<h5> &nbsp&nbsp&nbspZitong Zhao</h5>
							<p> &nbsp&nbsp&nbsp2453357Z</p>
						</div>
						</br>
						
					</div>
					</br>
					</br>
					</br>
					</br>
				</div>
			</section>

{% endblock %}

templates/doggie/add_dog.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Dog
{% endblock %}

{% block body_block %}
<section id="main" >
<div class="inner">
        <h3>Add a Dog </h3>
        <br/>
        <div>
        
            <form id="add_dog_form" method="post" enctype="multipart/form-data" action="/doggie/add_dog/">
                {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        <div>
                            {{ field.errors }}
                            <strong>{{ field.help_text }}</strong>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <br/>
                <input type="submit" name="submit" value="Add Dog" />
            </form>
        </div>
        </div>
        </section>
{% endblock %}

templates/doggie/add_dogcategory.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Dogcategory
{% endblock %}

{% block body_block %}
<section id="main" >
<div class="inner">
        <h3>Add a DogCategory</h3>
        <br/>
        <div>
            <form id="dogcategory_form" method="post" action="/doggie/add_dogcategory/">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}
                    {{ field }}
                {% endfor %}
                <br/>
                 <input type="submit" name="submit" value="Create DogCategory" />
            </form>
            <br/>
            <br/>
              <br/>
                <br/>
                  <br/>
          </div>
          </div>
          </section>
{% endblock %}

templates/doggie/base.html
<!DOCTYPE html>
{%load staticfiles%}
{% load doggie_template_tags %}

<html>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <!-- Js -->
    <script src="{% static 'js/doggie-ajax.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/skel.min.js' %}"></script>
	<script src="{% static 'js/util.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
    <head>
        <title>
            Doggie -
            {% block title_block %}
               Doggie!
            {% endblock %}
        </title>
    </head>

    <body>

        <div>
         {% block body_block %}
        {% endblock %}
        </div>

			<header id="header">
				<div class="inner">
					<a href="{% url 'doggie:index' %}" class="logo">DoggieBook</a>
			 <nav id="nav">
			<a href="{% url 'doggie:index' %}">Home</a>
			<a href="{% url 'doggie:about' %}">About</a>
       {% if user.is_authenticated %}
            <a href="{% url 'doggie:profile' user.username %}">Profile</a>
            <a href="{% url 'auth_logout' %}?next={% url 'doggie:index' %}">Logout</a>
        {% else %}
            <a href="{% url 'registration_register'%}">Register</a>
            <a href="{% url 'auth_login' %}">Login</a>
     {% endif %} 


</nav>


</div>
</header>
		 <a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>

        		<!-- Footer -->
			<section id="footer">
				<div class="inner">
					<div>
					Produced by Group X, 2019-2020, IT, University of Glasgow
					</div>
				</div>
			</section>

        </body>
</html>

templates/doggie/comment_list.html
<section id="main" >
<div class="inner" style=margin-left:-2px;>
  <strong><a>Comment</a></strong>
  </br>
{% for cmt in cmt_list %}
  <a><i><h5>({{forloop.counter}}#)&nbsp;&nbsp;&nbsp;</h5></i>
  <h5>{{cmt.owner}}</h5>
  <P>{{cmt.body}}</p>
  <p style="font-size:14px">{{cmt.create_date}}</p></a>
  <hr>
{% empty %}
<p>There is no comment yet. Be the first to say something:)<p>
{% endfor %}
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<script type="text/javascript">
$(function() {
    $("#cmt_submit").click(function(){
        var body = $("#cmt_content").val();
        if (body.length == 0){
            alert("Please enter comment....");
            return;
        }


        var dog_id = $(this).data('dog_id');
        var csrf = $(this).data('csrf');
        var ajax_url = $(this).data('ajax_url')


        var post_data={
        "dog_id":dog_id,
        "body":body,
        };

        $.ajaxSetup({
            data:{'csrfmiddlewaretoken': csrf }
        });

        $.ajax({
            url:ajax_url,
            type:'post',
            data:post_data,

            success:function (data) {
                alert(data.msg);
                window.location.reload();
            },

            error:function (data) {
                alert("err"+ data.msg);
            }
        });
    });
})
</script>

<div class="inner" style=margin-left:-2px;>
{% if user.is_authenticated %}
  <textarea rows="5" cols="100" id="cmt_content"></textarea>
  <br>
  <button type="button alt" id="cmt_submit" onclick="comment()"
          data-csrf="{{ csrf_token }}" data-dog_id="{{dog.id}}" data-ajax_url="add/">Comment</button>
{% else %}
  <div>You are not logged in and cannot comment right now. Please first
      <a class="text-danger contentlink" href="{% url 'auth_login' %}?next={{ request.path }}">Login</a> or
      <a class="text-danger contentlink" href="{% url 'registration_register' %}?next={{ request.path }}">Register</a>
  </div>
{% endif %}
  <br><br><br>
</div>
</section>

templates/doggie/dog.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    This a dog
{% endblock %}

{% block body_block %}

        {% if dogs %}
            {% for dog in dogs %}
            <section id="main" >
          
<div class="inner">
           <div><h3>{{ dog.dog_name}} <h3></div>
            <div>
            <img src="{{ MEDIA_URL }}{{ dog.images }}"width="350px" height="350px"> </br></br>
            <strong> Dog Name</strong> </br> {{ dog.dog_name}} </br></br>
            <strong> Introduction</strong> </br> {{ dog.long_description}} </br></br>
            <strong> Life Span</strong> </br> {{ dog.life_span}} </br></br>
            <strong> Price (£)</strong> </br>  {{ dog.price}} </br></br>
            </div>
        <div>
         {% if user.is_authenticated %}
       <button id="likes" data-recipeid="{{dog.id}}"
                                                class="button alt" onclick="saveLikes()" type="button" >
                                                <i class="fa fa-thumbs-up"></i>
                                                        &ensp;Like
                                                </button>
                                                {% endif %}
                                                </br>
                                                <strong id="like_count">{{ dog.likes }}</strong> people like this dog
        </div>
        
         <div>

            {% endfor %}
        {% else %}
        <strong>No dog!</strong>
        {% endif %}
        </br>
    
        </div>
       
       
        {% include 'doggie/comment_list.html'%}
            <button onclick="window.history.back()">Go back</button>
        
        </div>
             </section>
{% endblock %}

templates/doggie/dogcategories.html
<section id="main" >
<div class="inner">
<ul>
{% if dogcategories %}
    {% for c in dogcategories %}
        {% if c == current_dogcategory %}
        <li><strong><a href="{% url 'doggie:show_dogcategory' c.slug %}">{{ c.name }}<hr /></a></strong></li>
        {% else %}
        <li><a href="{% url 'doggie:show_dogcategory' c.slug %}">{{ c.name }}<hr /></a></li>
        {% endif %}
    {% endfor %}
{% else %}
    <li><strong>There are no dogcategories present.</strong></li>
{% endif %}
</ul>
</div>
</section>

templates/doggie/dogcategory.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    This a dogcategory
{% endblock %}

{% block body_block %}
<section id="main">
<div class="inner">
        {% if dogcategory %}
            <h3>{{ dogcategory.name|linebreaksbr }}</h3>
            </br>
            {% if dogs %}
            <ul style=padding:-25px;>
                {% for dog in dogs %}
                <img src="{{ MEDIA_URL }}{{ dog.images }}" width="150px" height="150px">
                <li style="list-style-type:none; margin:-8px; padding-bottom:8px;"><strong><a style="color:#e5474b" href="/doggie/dogcategory/{{ dogcategory.slug }}/{{ dog.slug }}/">{{ dog.dog_name }}</a></strong></li>
                <p style="max-width:350px; line-height:26px;">{{ dog.short_description }}<hr /></p>
                {% endfor %}
            </ul>
            {% else %}
            <strong>No dogs currently in dogcategory.</strong>
            {% endif %}
            <a href="/doggie/add_dog/" class="contentlink"> Add a New Dog</a> <br />
        {% else %}
            The specified dogcategory does not exist.
        {% endif %}
        <br/>
         <button onclick="window.history.back()">Go back</button>
        </div>
        </section>
{% endblock %}

templates/doggie/index.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}




		<!-- Banner -->
	<section id="banner" >
		<div class="inner">
			<h1>HAPPINESS IS A WARM DOG.</h1>
			 <div>
              {% if user.is_authenticated %}
           <strong class="greeting"> Welcome! {{ user.username }}</strong>
             {% else %}
              <strong class="greeting"> Hey guest!</strong>
             {% endif %}
<!-- 
             <br />
            <strong>{{ boldmessage }}</strong><br />
 -->
        </div>
			 <p style="color:#d7d7d7;font-size:18px"> We have got {{ visits }} vistors</p>
			 <div class="search">
             <div>
<!-- 
                <button class="searchbtn type="button">
                <a href="/search/">
                search</a></button>
 -->
               <a href="/search/" class="button">search</a>
              </div>

		</div>

	</section>


            <section id="three">

				<div class="inner">
		 {% if dogcategories %}

        {% for dogcategory in dogcategories %}	
				 {% if dogcategory.slug == 'small-dog' %}
					<article>
						<div class="content">
                    
                        <img src="/media/images/icon/hsk.png" alt="small dog" />
							<header>
								<h3>small dogs</h3>
							</header>
							<p>Small dogs are suitable for living in the city. Most of them are cheerful, lively, docile and lively.</p>
							<ul class="actions">
								<li><a href="{% url 'doggie:show_dogcategory' dogcategory.slug %}" class="button alt">Learn More</a></li>
							</ul>
						</div>
					</article>
					

					
				  {% elif dogcategory.slug == 'medium-dog' %}
					<article>
					 	<div class="content">
					
                           <img src="/media/images/icon/gou.png" alt="medium dog" />
							<header>
								<h3>medium dogs</h3>
							</header>
							<p>The medium sized dogs are gentle with people. Most of them can even help take care of the children.</p>
							<ul class="actions">
								<li><a href="{% url 'doggie:show_dogcategory' dogcategory.slug %}" class="button alt">Learn More</a></li>
							</ul>
						</div>
					</article>
					
					 {% elif dogcategory.slug == 'large-dog' %}
					<article>
					<div class="content">
					
                    <img src="/media/images/icon/jm.png" alt="big dog" />
							<header>
								<h3>large dogs</h3>
							</header>
							<p>The large sized dogs provide security and they can guard the house. They have territorial awareness.</p>
							<ul class="actions">
								<li><a href="{% url 'doggie:show_dogcategory' dogcategory.slug %}" class="button alt">Learn More</a></li>
							</ul>
					    </div>
					</article>
        {% endif %}
        {% endfor %}

        {% else %}
            <strong>There are no dogcategories present.</strong>
        {% endif %}
						</div>
				</div>
			</section>


{% endblock %}

templates/doggie/profile.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
<section id="main" >
<div class="inner">
        <h3>{{ selected_user.username }}'s Profile</h3>
<br/>

        {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}" width="300" height="300" alt="{{ selected_user.username }}'s profile image" />
        {% else %}
        <img src="https://lorempixel.com/300/300/people/" width="300" height="300" alt="Placeholder image" />
        {% endif %}
        <br />
        <div>
            {% if selected_user == user %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Update" />
            </form>
            {% else %}

            {% endif %}
            <a href="{% url 'auth_password_change' %}" class="contentlink">Change your Password</a><br/>
<!--         <a href="{% url 'doggie:add_dogcategory' %}" class="contentlink">Add a New Category</a><br />   -->
<!--             <a href="{% url 'doggie:add_dog' %}" class="contentlink">Add a New Dog</a><br /> -->
        </div>
        </div>
</section>
{% endblock %}

templates/doggie/profile_registration.html
{% extends 'doggie/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register - 2
{% endblock %}

{% block body_block %}

<section id="main" >
<div class="inner">
<h3>Registration - Step 2</h3>
</br>
<form method="post" action="{% url 'doggie:register_profile' %}" enctype="multipart/form-data">
{% csrf_token %}

{{ form.as_p }}
<input type="submit" value="Create Profile" />
</form>

</div>
</section>
{% endblock %}